import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/Components/Navbar";
import { PageDescription } from "@/Components/PageDescription";
import SortMethods from "@/Components/SortMethods";
import Bloglist from "@/Components/Bloglist";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <PageDescription />
        <section id="content" className={styles.center}>
          <SortMethods />
          <Bloglist />
        </section>
      </main>
    </>
  );
}
